set noswapfile
set autoindent
"set number
set expandtab
set tabstop=4
set colorcolumn=80
"set mouse=a
set ruler
" Make backspace behave like other editors
set backspace=2
" Disable .viminfo file
set viminfo=

syntax on
highlight ColorColumn ctermbg=black
highlight ExtraWhitespace ctermbg=red guibg=red
highlight Tab ctermbg=red
match ExtraWhitespace /\s+$/
match Tab /\t/

" vimdiff highlighting
highlight DiffAdd    cterm=bold ctermbg=22
highlight DiffDelete cterm=bold ctermbg=88
highlight DiffChange            ctermbg=17
highlight DiffText   cterm=bold ctermbg=12

call plug#begin('~/.vim/plugged')

Plug 'editorconfig/editorconfig-vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'mattn/vim-lsp-settings'

call plug#end()
