#!/bin/bash
# This hook is sourced after every virtualenv is activated.

# This links a gcloud configuration to a virtualenv. See:
#
#   gcloud config configurations list
CLOUDSDK_ACTIVE_CONFIG_NAME="$(basename "$VIRTUAL_ENV")"

export CLOUDSDK_ACTIVE_CONFIG_NAME


POSTACTIVATE="$PWD/.git/virtualenvwrapper/postactivate"
if [ -f "$POSTACTIVATE" ]; then
  source "$POSTACTIVATE"
fi
unset POSTACTIVATE


function ptw {
  if [ ! -x "$VIRTUAL_ENV/bin/ptw" ]; then
    "$VIRTUAL_ENV/bin/pip" install pytest-watch
  fi
  "$VIRTUAL_ENV/bin/ptw" "$@"
}


function sphinx-autobuild {
  if [ ! -x "$VIRTUAL_ENV/bin/sphinx-autobuild" ]; then
    "$VIRTUAL_ENV/bin/pip" install sphinx-autobuild
  fi
  "$VIRTUAL_ENV/bin/sphinx-autobuild" "$@"
}
