#!/bin/bash
# This hook is sourced after every virtualenv is deactivated.

POSTDEACTIVATE="$PWD/.git/virtualenvwrapper/postactivate"
if [ -f "$POSTDEACTIVATE" ]; then
  source "$POSTDEACTIVATE"
fi
unset POSTDEACTIVATE
unset CLOUDSDK_ACTIVE_CONFIG_NAME
unset -f ptw
unset -f sphinx-autobuild
